2022-10-20 11:26:03,091  ###################################################### New MAIN run
2022-10-20 11:26:03,092  ##################### New run
2022-10-20 11:26:03,093  ##### Run updateGroupsMapping
2022-10-20 11:26:03,095  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 11:26:03,095  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 11:26:03,265  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 11:26:03,268  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 11:26:03,269  ### Processing group: -1001683374540
2022-10-20 11:26:03,269  Time interval passed. Sending message
2022-10-20 11:26:03,270  Error when sending Telegram message: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.png'
2022-10-20 11:26:03,271  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/tgsenmph/tgsenmesph.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.png'

2022-10-20 11:26:03,273  Error, message not sent.
2022-10-20 11:26:03,273  Sleeping 1800 seconds.
2022-10-20 11:33:34,434  Quit
2022-10-20 11:33:36,337  ###################################################### New MAIN run
2022-10-20 11:33:36,338  ##################### New run
2022-10-20 11:33:36,339  ##### Run updateGroupsMapping
2022-10-20 11:33:36,341  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 11:33:36,342  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 11:33:36,510  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 11:33:36,511  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 11:33:36,512  ### Processing group: -1001683374540
2022-10-20 11:33:36,512  Time interval passed. Sending message
2022-10-20 11:33:36,513  Error when sending Telegram message: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.png/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/img.png'
2022-10-20 11:33:36,515  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/tgsenmph/tgsenmesph.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/pig.png/var/local/randomScriptsAndProjects/telegramBotSendMessageToGroupsWithPicturesUsingTelepot/img.png'

2022-10-20 11:33:36,517  Error, message not sent.
2022-10-20 11:33:36,517  Sleeping 1800 seconds.
2022-10-20 11:34:16,062  Quit
2022-10-20 11:34:17,338  ###################################################### New MAIN run
2022-10-20 11:34:17,339  ##################### New run
2022-10-20 11:34:17,339  ##### Run updateGroupsMapping
2022-10-20 11:34:17,341  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 11:34:17,342  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 11:34:17,517  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 11:34:17,519  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 11:34:17,520  ### Processing group: -1001683374540
2022-10-20 11:34:17,520  Time interval passed. Sending message
2022-10-20 11:34:17,521  Error when sending Telegram message: [Errno 20] Not a directory: '/var/local/randomScriptsAndProjects/tgsenmph/pig.png/var/local/randomScriptsAndProjects/tgsenmph/img.png'
2022-10-20 11:34:17,522  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/tgsenmph/tgsenmesph.py", line 62, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
NotADirectoryError: [Errno 20] Not a directory: '/var/local/randomScriptsAndProjects/tgsenmph/pig.png/var/local/randomScriptsAndProjects/tgsenmph/img.png'

2022-10-20 11:34:17,524  Error, message not sent.
2022-10-20 11:34:17,524  Sleeping 1800 seconds.
2022-10-20 11:37:03,294  Quit
2022-10-20 11:37:04,379  ###################################################### New MAIN run
2022-10-20 11:37:04,380  ##################### New run
2022-10-20 11:37:04,380  ##### Run updateGroupsMapping
2022-10-20 11:37:04,382  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 11:37:04,383  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 11:37:04,573  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 11:37:04,574  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 11:37:04,574  ### Processing group: -1001683374540
2022-10-20 11:37:04,574  Time interval passed. Sending message
2022-10-20 11:37:04,584  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 11:37:04,585  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 11:37:04,866  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 963
2022-10-20 11:37:04,868  Message successfully sent.
2022-10-20 11:37:04,868  Sleeping 1800 seconds.
2022-10-20 11:37:45,584  Quit
2022-10-20 11:37:46,776  ###################################################### New MAIN run
2022-10-20 11:37:46,777  ##################### New run
2022-10-20 11:37:46,778  ##### Run updateGroupsMapping
2022-10-20 11:37:46,781  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 11:37:46,782  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 11:37:46,939  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 11:37:46,941  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 11:37:46,941  ### Processing group: -1001683374540
2022-10-20 11:37:46,942  Time interval passed. Sending message
2022-10-20 11:37:46,953  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 11:37:46,954  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 11:37:47,161  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 951
2022-10-20 11:37:47,163  Message successfully sent.
2022-10-20 11:37:47,163  Sleeping 1800 seconds.
2022-10-20 12:07:47,246  ##################### New run
2022-10-20 12:07:47,250  ##### Run updateGroupsMapping
2022-10-20 12:07:47,254  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 12:07:47,256  Resetting dropped connection: api.telegram.org
2022-10-20 12:07:47,412  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 12:07:47,414  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666255066.942049}}
2022-10-20 12:07:47,414  ### Processing group: -1001683374540
2022-10-20 12:07:47,415  Time interval passed. Sending message
2022-10-20 12:07:47,416  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 12:07:47,417  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 12:07:47,637  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 951
2022-10-20 12:07:47,639  Message successfully sent.
2022-10-20 12:07:47,639  Sleeping 1800 seconds.
2022-10-20 12:37:47,724  ##################### New run
2022-10-20 12:37:47,727  ##### Run updateGroupsMapping
2022-10-20 12:37:47,731  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 12:37:47,734  Resetting dropped connection: api.telegram.org
2022-10-20 12:37:47,909  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 12:37:47,910  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666256867.4151351}}
2022-10-20 12:37:47,910  ### Processing group: -1001683374540
2022-10-20 12:37:47,911  Time interval passed. Sending message
2022-10-20 12:37:47,916  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 12:37:47,917  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 12:37:48,873  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 200 1450
2022-10-20 12:37:48,875  Message successfully sent.
2022-10-20 12:37:48,876  Sleeping 1800 seconds.
2022-10-20 13:07:48,964  ##################### New run
2022-10-20 13:07:48,968  ##### Run updateGroupsMapping
2022-10-20 13:07:48,969  Error when reading groups mapping for bot: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/tgsenmph/mapping.txt'
2022-10-20 13:07:48,970  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/tgsenmph/tgsenmesph.py", line 77, in readGroupsMapping
FileNotFoundError: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/tgsenmph/mapping.txt'

2022-10-20 13:07:48,974  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 13:07:48,976  Resetting dropped connection: api.telegram.org
2022-10-20 13:07:49,146  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 13:07:49,148  Fatal Error: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/tgsenmph/groups.txt'
2022-10-20 13:07:49,149  Traceback (most recent call last):
  File "/var/local/randomScriptsAndProjects/tgsenmph/tgsenmesph.py", line 199, in mainFunction
  File "/var/local/randomScriptsAndProjects/tgsenmph/tgsenmesph.py", line 146, in readGroups
FileNotFoundError: [Errno 2] No such file or directory: '/var/local/randomScriptsAndProjects/tgsenmph/groups.txt'

