2022-10-20 14:36:07,502  ###################################################### New MAIN run
2022-10-20 14:36:07,503  Message file message.txt not found. Exiting.
2022-10-20 14:36:07,503  Picture file picturePath.txt not found. Exiting.
2022-10-20 14:36:07,504  ##################### New run
2022-10-20 14:36:07,504  ##### Run updateGroupsMapping
2022-10-20 14:36:07,506  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:36:07,506  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 14:36:07,689  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 14:36:07,690  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 14:36:07,691  ### Processing group: -1001683374540
2022-10-20 14:36:07,691  Time interval passed. Sending message
2022-10-20 14:36:07,699  Error when sending Telegram message: [Errno 2] No such file or directory: 'AgACAgIAAxkBAAJLu2M3AAEpNxjSrKsXr_Ru_X2Kq6UBZQAC2b8xG6peuElaG2N1oLpcPgEAAwIAA3kAAyoE'
2022-10-20 14:36:07,700  Traceback (most recent call last):
  File "/var/local/bot3101f/tgsenmesph.py", line 66, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=open(picturePathToSend, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'AgACAgIAAxkBAAJLu2M3AAEpNxjSrKsXr_Ru_X2Kq6UBZQAC2b8xG6peuElaG2N1oLpcPgEAAwIAA3kAAyoE'

2022-10-20 14:36:07,702  Error, message not sent.
2022-10-20 14:36:07,702  Sleeping 1800 seconds.
2022-10-20 14:36:21,926  Quit
2022-10-20 14:43:28,105  ###################################################### New MAIN run
2022-10-20 14:43:28,107  Message file message.txt not found. Exiting.
2022-10-20 14:43:28,107  Picture file picturePath.txt not found. Exiting.
2022-10-20 14:43:28,108  ##################### New run
2022-10-20 14:43:28,108  ##### Run updateGroupsMapping
2022-10-20 14:43:28,111  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:43:28,111  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 14:43:28,278  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 14:43:28,280  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 14:43:28,280  ### Processing group: -1001683374540
2022-10-20 14:43:28,280  Time interval passed. Sending message
2022-10-20 14:43:28,287  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:43:28,417  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 400 99
2022-10-20 14:43:28,419  Error when sending Telegram message: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})
2022-10-20 14:43:28,421  Traceback (most recent call last):
  File "/var/local/bot3101f/tgsenmesph.py", line 66, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=picturePathToSend) #photo=open(picturePathToSend, "rb")
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 539, in sendPhoto
    return self._api_request_with_file('sendPhoto', _rectify(p), 'photo', photo)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 496, in _api_request_with_file
    return self._api_request(method, _rectify(params), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})

2022-10-20 14:43:28,424  Error, message not sent.
2022-10-20 14:43:28,425  Sleeping 1800 seconds.
2022-10-20 14:44:16,721  Quit
2022-10-20 14:44:18,764  ###################################################### New MAIN run
2022-10-20 14:44:18,767  Message file message.txt not found. Exiting.
2022-10-20 14:44:18,768  Picture file picturePath.txt not found. Exiting.
2022-10-20 14:44:18,768  ##################### New run
2022-10-20 14:44:18,769  ##### Run updateGroupsMapping
2022-10-20 14:44:18,770  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:44:18,771  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 14:44:18,950  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 14:44:18,951  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 14:44:18,952  ### Processing group: -1001683374540
2022-10-20 14:44:18,952  Time interval passed. Sending message
2022-10-20 14:44:18,963  Error when sending Telegram message: 'NoneType' object has no attribute 'read'
2022-10-20 14:44:18,965  Traceback (most recent call last):
  File "/var/local/bot3101f/tgsenmesph.py", line 66, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=picturePathToSend) #photo=open(picturePathToSend, "rb")
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 539, in sendPhoto
    return self._api_request_with_file('sendPhoto', _rectify(p), 'photo', photo)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 499, in _api_request_with_file
    return self._api_request(method, _rectify(params), files, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 153, in request
    fn, args, kwargs = _transform(req, **user_kw)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 118, in _transform
    fields = _compose_fields(req, **user_kw)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 84, in _compose_fields
    fields.update({k:_filetuple(k,v) for k,v in files.items()})
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 84, in <dictcomp>
    fields.update({k:_filetuple(k,v) for k,v in files.items()})
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 61, in _filetuple
    return (_guess_filename(f) or key, f.read())
AttributeError: 'NoneType' object has no attribute 'read'

2022-10-20 14:44:18,970  Error, message not sent.
2022-10-20 14:44:18,970  Sleeping 30 seconds.
2022-10-20 14:44:48,993  ##################### New run
2022-10-20 14:44:48,995  ##### Run updateGroupsMapping
2022-10-20 14:44:48,997  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:44:49,051  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 14:44:49,052  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 14:44:49,053  ### Processing group: -1001683374540
2022-10-20 14:44:49,053  Time interval passed. Sending message
2022-10-20 14:44:49,060  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:44:49,217  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 400 99
2022-10-20 14:44:49,219  Error when sending Telegram message: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})
2022-10-20 14:44:49,220  Traceback (most recent call last):
  File "/var/local/bot3101f/tgsenmesph.py", line 66, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=picturePathToSend) #photo=open(picturePathToSend, "rb")
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 539, in sendPhoto
    return self._api_request_with_file('sendPhoto', _rectify(p), 'photo', photo)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 496, in _api_request_with_file
    return self._api_request(method, _rectify(params), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})

2022-10-20 14:44:49,223  Error, message not sent.
2022-10-20 14:44:49,224  Sleeping 30 seconds.
2022-10-20 14:45:19,236  ##################### New run
2022-10-20 14:45:19,238  ##### Run updateGroupsMapping
2022-10-20 14:45:19,241  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:45:19,306  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 14:45:19,307  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 14:45:19,308  ### Processing group: -1001683374540
2022-10-20 14:45:19,308  Time interval passed. Sending message
2022-10-20 14:45:19,316  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:45:19,392  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 400 99
2022-10-20 14:45:19,393  Error when sending Telegram message: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})
2022-10-20 14:45:19,393  Traceback (most recent call last):
  File "/var/local/bot3101f/tgsenmesph.py", line 66, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=picturePathToSend) #photo=open(picturePathToSend, "rb")
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 539, in sendPhoto
    return self._api_request_with_file('sendPhoto', _rectify(p), 'photo', photo)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 496, in _api_request_with_file
    return self._api_request(method, _rectify(params), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})

2022-10-20 14:45:19,398  Error, message not sent.
2022-10-20 14:45:19,398  Sleeping 30 seconds.
2022-10-20 14:45:43,685  Quit
2022-10-20 14:45:45,716  ###################################################### New MAIN run
2022-10-20 14:45:45,720  Message file message.txt not found. Exiting.
2022-10-20 14:45:45,721  Picture file picturePath.txt not found. Exiting.
2022-10-20 14:45:45,721  ##################### New run
2022-10-20 14:45:45,722  ##### Run updateGroupsMapping
2022-10-20 14:45:45,724  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:45:45,724  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 14:45:45,907  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 14:45:45,908  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 14:45:45,909  ### Processing group: -1001683374540
2022-10-20 14:45:45,909  Time interval passed. Sending message
2022-10-20 14:45:45,917  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:45:45,994  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 400 99
2022-10-20 14:45:45,996  Error when sending Telegram message: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})
2022-10-20 14:45:45,999  Traceback (most recent call last):
  File "/var/local/bot3101f/tgsenmesph.py", line 67, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=picturePathToSend) #photo=open(picturePathToSend, "rb")
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 539, in sendPhoto
    return self._api_request_with_file('sendPhoto', _rectify(p), 'photo', photo)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 496, in _api_request_with_file
    return self._api_request(method, _rectify(params), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})

2022-10-20 14:45:46,003  Error, message not sent.
2022-10-20 14:45:46,004  Sleeping 30 seconds.
2022-10-20 14:46:16,011  ##################### New run
2022-10-20 14:46:16,012  ##### Run updateGroupsMapping
2022-10-20 14:46:16,013  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:46:16,068  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 14:46:16,070  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 14:46:16,070  ### Processing group: -1001683374540
2022-10-20 14:46:16,071  Time interval passed. Sending message
2022-10-20 14:46:16,079  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:46:16,443  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 400 99
2022-10-20 14:46:16,444  Error when sending Telegram message: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})
2022-10-20 14:46:16,445  Traceback (most recent call last):
  File "/var/local/bot3101f/tgsenmesph.py", line 67, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=picturePathToSend) #photo=open(picturePathToSend, "rb")
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 539, in sendPhoto
    return self._api_request_with_file('sendPhoto', _rectify(p), 'photo', photo)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 496, in _api_request_with_file
    return self._api_request(method, _rectify(params), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})

2022-10-20 14:46:16,448  Error, message not sent.
2022-10-20 14:46:16,448  Sleeping 30 seconds.
2022-10-20 14:46:46,480  ##################### New run
2022-10-20 14:46:46,482  ##### Run updateGroupsMapping
2022-10-20 14:46:46,485  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:46:46,536  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 14:46:46,538  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 14:46:46,538  ### Processing group: -1001683374540
2022-10-20 14:46:46,539  Time interval passed. Sending message
2022-10-20 14:46:46,547  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:46:46,613  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 400 99
2022-10-20 14:46:46,615  Error when sending Telegram message: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})
2022-10-20 14:46:46,616  Traceback (most recent call last):
  File "/var/local/bot3101f/tgsenmesph.py", line 67, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=picturePathToSend) #photo=open(picturePathToSend, "rb")
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 539, in sendPhoto
    return self._api_request_with_file('sendPhoto', _rectify(p), 'photo', photo)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 496, in _api_request_with_file
    return self._api_request(method, _rectify(params), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})

2022-10-20 14:46:46,619  Error, message not sent.
2022-10-20 14:46:46,619  Sleeping 30 seconds.
2022-10-20 14:47:16,648  ##################### New run
2022-10-20 14:47:16,650  ##### Run updateGroupsMapping
2022-10-20 14:47:16,652  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:47:16,712  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 14:47:16,714  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 14:47:16,714  ### Processing group: -1001683374540
2022-10-20 14:47:16,714  Time interval passed. Sending message
2022-10-20 14:47:16,722  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:47:16,821  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 400 99
2022-10-20 14:47:16,822  Error when sending Telegram message: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})
2022-10-20 14:47:16,823  Traceback (most recent call last):
  File "/var/local/bot3101f/tgsenmesph.py", line 67, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=picturePathToSend) #photo=open(picturePathToSend, "rb")
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 539, in sendPhoto
    return self._api_request_with_file('sendPhoto', _rectify(p), 'photo', photo)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 496, in _api_request_with_file
    return self._api_request(method, _rectify(params), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})

2022-10-20 14:47:16,827  Error, message not sent.
2022-10-20 14:47:16,827  Sleeping 30 seconds.
2022-10-20 14:47:46,834  ##################### New run
2022-10-20 14:47:46,836  ##### Run updateGroupsMapping
2022-10-20 14:47:46,839  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:47:46,897  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 14:47:46,899  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 14:47:46,900  ### Processing group: -1001683374540
2022-10-20 14:47:46,900  Time interval passed. Sending message
2022-10-20 14:47:46,907  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:47:46,973  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 400 99
2022-10-20 14:47:46,974  Error when sending Telegram message: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})
2022-10-20 14:47:46,975  Traceback (most recent call last):
  File "/var/local/bot3101f/tgsenmesph.py", line 67, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=picturePathToSend) #photo=open(picturePathToSend, "rb")
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 539, in sendPhoto
    return self._api_request_with_file('sendPhoto', _rectify(p), 'photo', photo)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 496, in _api_request_with_file
    return self._api_request(method, _rectify(params), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})

2022-10-20 14:47:46,979  Error, message not sent.
2022-10-20 14:47:46,980  Sleeping 30 seconds.
2022-10-20 14:48:17,011  ##################### New run
2022-10-20 14:48:17,011  ##### Run updateGroupsMapping
2022-10-20 14:48:17,013  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:48:17,068  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 14:48:17,069  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 14:48:17,070  ### Processing group: -1001683374540
2022-10-20 14:48:17,070  Time interval passed. Sending message
2022-10-20 14:48:17,076  Error when sending Telegram message: 'NoneType' object has no attribute 'read'
2022-10-20 14:48:17,078  Traceback (most recent call last):
  File "/var/local/bot3101f/tgsenmesph.py", line 67, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=picturePathToSend) #photo=open(picturePathToSend, "rb")
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 539, in sendPhoto
    return self._api_request_with_file('sendPhoto', _rectify(p), 'photo', photo)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 499, in _api_request_with_file
    return self._api_request(method, _rectify(params), files, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 153, in request
    fn, args, kwargs = _transform(req, **user_kw)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 118, in _transform
    fields = _compose_fields(req, **user_kw)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 84, in _compose_fields
    fields.update({k:_filetuple(k,v) for k,v in files.items()})
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 84, in <dictcomp>
    fields.update({k:_filetuple(k,v) for k,v in files.items()})
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 61, in _filetuple
    return (_guess_filename(f) or key, f.read())
AttributeError: 'NoneType' object has no attribute 'read'

2022-10-20 14:48:17,081  Error, message not sent.
2022-10-20 14:48:17,081  Sleeping 30 seconds.
2022-10-20 14:48:33,928  Quit
2022-10-20 14:48:36,360  ###################################################### New MAIN run
2022-10-20 14:48:36,364  Message file message.txt not found. Exiting.
2022-10-20 14:48:36,364  Picture file picturePath.txt not found. Exiting.
2022-10-20 14:48:36,365  ##################### New run
2022-10-20 14:48:36,365  ##### Run updateGroupsMapping
2022-10-20 14:48:36,368  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:48:36,368  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 14:48:36,564  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 14:48:36,566  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 14:48:36,567  ### Processing group: -1001683374540
2022-10-20 14:48:36,567  Time interval passed. Sending message
2022-10-20 14:48:36,575  Message successfully sent.
2022-10-20 14:48:36,576  Sleeping 30 seconds.
2022-10-20 14:49:06,588  ##################### New run
2022-10-20 14:49:06,591  ##### Run updateGroupsMapping
2022-10-20 14:49:06,593  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:49:06,646  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 14:49:06,648  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666266516.5677378}}
2022-10-20 14:49:06,649  ### Processing group: -1001683374540
2022-10-20 14:49:06,649  Time interval not already passed. Wait 149.91812944412231 seconds.
2022-10-20 14:49:06,649  Sleeping 30 seconds.
2022-10-20 14:49:36,668  ##################### New run
2022-10-20 14:49:36,671  ##### Run updateGroupsMapping
2022-10-20 14:49:36,673  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:49:36,725  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1038
2022-10-20 14:49:36,727  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666266516.5677378}}
2022-10-20 14:49:36,727  ### Processing group: -1001683374540
2022-10-20 14:49:36,728  Time interval not already passed. Wait 119.83935403823853 seconds.
2022-10-20 14:49:36,729  Sleeping 30 seconds.
2022-10-20 14:50:06,760  ##################### New run
2022-10-20 14:50:06,763  ##### Run updateGroupsMapping
2022-10-20 14:50:06,766  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:50:06,827  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 1399
2022-10-20 14:50:06,830  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666266516.5677378}}
2022-10-20 14:50:06,830  ### Processing group: -1001683374540
2022-10-20 14:50:06,831  Time interval not already passed. Wait 89.73672771453857 seconds.
2022-10-20 14:50:06,831  Sleeping 30 seconds.
2022-10-20 14:50:36,848  ##################### New run
2022-10-20 14:50:36,850  ##### Run updateGroupsMapping
2022-10-20 14:50:36,853  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:50:36,905  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 14:50:36,906  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666266516.5677378}}
2022-10-20 14:50:36,907  ### Processing group: -1001683374540
2022-10-20 14:50:36,908  Time interval not already passed. Wait 59.659539461135864 seconds.
2022-10-20 14:50:36,908  Sleeping 30 seconds.
2022-10-20 14:51:06,936  ##################### New run
2022-10-20 14:51:06,939  ##### Run updateGroupsMapping
2022-10-20 14:51:06,943  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:51:07,003  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 14:51:07,004  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666266516.5677378}}
2022-10-20 14:51:07,005  ### Processing group: -1001683374540
2022-10-20 14:51:07,005  Time interval not already passed. Wait 29.562013864517212 seconds.
2022-10-20 14:51:07,006  Sleeping 30 seconds.
2022-10-20 14:51:37,028  ##################### New run
2022-10-20 14:51:37,031  ##### Run updateGroupsMapping
2022-10-20 14:51:37,035  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:51:37,094  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 14:51:37,095  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666266516.5677378}}
2022-10-20 14:51:37,096  ### Processing group: -1001683374540
2022-10-20 14:51:37,096  Time interval passed. Sending message
2022-10-20 14:51:37,102  Message successfully sent.
2022-10-20 14:51:37,103  Sleeping 30 seconds.
2022-10-20 14:52:07,134  ##################### New run
2022-10-20 14:52:07,136  ##### Run updateGroupsMapping
2022-10-20 14:52:07,137  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:52:07,189  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 14:52:07,190  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666266697.0965867}}
2022-10-20 14:52:07,191  ### Processing group: -1001683374540
2022-10-20 14:52:07,191  Time interval not already passed. Wait 149.90492415428162 seconds.
2022-10-20 14:52:07,192  Sleeping 30 seconds.
2022-10-20 14:52:37,215  ##################### New run
2022-10-20 14:52:37,220  ##### Run updateGroupsMapping
2022-10-20 14:52:37,224  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:52:37,280  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 14:52:37,281  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666266697.0965867}}
2022-10-20 14:52:37,282  ### Processing group: -1001683374540
2022-10-20 14:52:37,282  Time interval not already passed. Wait 119.81405377388 seconds.
2022-10-20 14:52:37,282  Sleeping 30 seconds.
2022-10-20 14:53:07,308  ##################### New run
2022-10-20 14:53:07,310  ##### Run updateGroupsMapping
2022-10-20 14:53:07,313  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:53:07,367  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 14:53:07,368  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666266697.0965867}}
2022-10-20 14:53:07,369  ### Processing group: -1001683374540
2022-10-20 14:53:07,369  Time interval not already passed. Wait 89.7271831035614 seconds.
2022-10-20 14:53:07,369  Sleeping 30 seconds.
2022-10-20 14:53:37,372  ##################### New run
2022-10-20 14:53:37,372  ##### Run updateGroupsMapping
2022-10-20 14:53:37,374  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:53:37,439  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 14:53:37,441  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666266697.0965867}}
2022-10-20 14:53:37,442  ### Processing group: -1001683374540
2022-10-20 14:53:37,442  Time interval not already passed. Wait 59.65396428108215 seconds.
2022-10-20 14:53:37,443  Sleeping 30 seconds.
2022-10-20 14:54:07,444  ##################### New run
2022-10-20 14:54:07,446  ##### Run updateGroupsMapping
2022-10-20 14:54:07,448  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:54:07,502  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 14:54:07,504  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666266697.0965867}}
2022-10-20 14:54:07,504  ### Processing group: -1001683374540
2022-10-20 14:54:07,504  Time interval not already passed. Wait 29.59163212776184 seconds.
2022-10-20 14:54:07,505  Sleeping 30 seconds.
2022-10-20 14:54:37,534  ##################### New run
2022-10-20 14:54:37,538  ##### Run updateGroupsMapping
2022-10-20 14:54:37,542  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:54:37,597  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 14:54:37,599  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666266697.0965867}}
2022-10-20 14:54:37,600  ### Processing group: -1001683374540
2022-10-20 14:54:37,600  Time interval passed. Sending message
2022-10-20 14:54:37,622  Message successfully sent.
2022-10-20 14:54:37,622  Sleeping 30 seconds.
2022-10-20 14:55:07,640  ##################### New run
2022-10-20 14:55:07,643  ##### Run updateGroupsMapping
2022-10-20 14:55:07,645  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:55:07,697  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 14:55:07,699  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666266877.6009572}}
2022-10-20 14:55:07,699  ### Processing group: -1001683374540
2022-10-20 14:55:07,700  Time interval not already passed. Wait 149.90075302124023 seconds.
2022-10-20 14:55:07,700  Sleeping 30 seconds.
2022-10-20 14:55:37,704  ##################### New run
2022-10-20 14:55:37,710  ##### Run updateGroupsMapping
2022-10-20 14:55:37,714  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:55:37,768  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 14:55:37,770  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666266877.6009572}}
2022-10-20 14:55:37,771  ### Processing group: -1001683374540
2022-10-20 14:55:37,771  Time interval not already passed. Wait 119.82942152023315 seconds.
2022-10-20 14:55:37,772  Sleeping 30 seconds.
2022-10-20 14:56:07,788  ##################### New run
2022-10-20 14:56:07,792  ##### Run updateGroupsMapping
2022-10-20 14:56:07,796  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:56:07,849  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 14:56:07,853  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666266877.6009572}}
2022-10-20 14:56:07,854  ### Processing group: -1001683374540
2022-10-20 14:56:07,855  Time interval not already passed. Wait 89.74562549591064 seconds.
2022-10-20 14:56:07,855  Sleeping 30 seconds.
2022-10-20 14:56:37,875  ##################### New run
2022-10-20 14:56:37,877  ##### Run updateGroupsMapping
2022-10-20 14:56:37,880  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:56:37,940  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 14:56:37,942  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666266877.6009572}}
2022-10-20 14:56:37,942  ### Processing group: -1001683374540
2022-10-20 14:56:37,942  Time interval not already passed. Wait 59.658275842666626 seconds.
2022-10-20 14:56:37,943  Sleeping 30 seconds.
2022-10-20 14:57:07,972  ##################### New run
2022-10-20 14:57:07,975  ##### Run updateGroupsMapping
2022-10-20 14:57:07,980  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:57:08,034  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 14:57:08,036  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666266877.6009572}}
2022-10-20 14:57:08,037  ### Processing group: -1001683374540
2022-10-20 14:57:08,037  Time interval not already passed. Wait 29.563387632369995 seconds.
2022-10-20 14:57:08,038  Sleeping 30 seconds.
2022-10-20 14:57:38,068  ##################### New run
2022-10-20 14:57:38,069  ##### Run updateGroupsMapping
2022-10-20 14:57:38,070  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:57:38,127  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 14:57:38,128  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666266877.6009572}}
2022-10-20 14:57:38,129  ### Processing group: -1001683374540
2022-10-20 14:57:38,129  Time interval passed. Sending message
2022-10-20 14:57:38,136  Message successfully sent.
2022-10-20 14:57:38,137  Sleeping 30 seconds.
2022-10-20 14:58:08,148  ##################### New run
2022-10-20 14:58:08,150  ##### Run updateGroupsMapping
2022-10-20 14:58:08,153  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:58:08,214  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 14:58:08,216  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666267058.1294963}}
2022-10-20 14:58:08,217  ### Processing group: -1001683374540
2022-10-20 14:58:08,217  Time interval not already passed. Wait 149.91159772872925 seconds.
2022-10-20 14:58:08,218  Sleeping 30 seconds.
2022-10-20 14:58:38,240  ##################### New run
2022-10-20 14:58:38,242  ##### Run updateGroupsMapping
2022-10-20 14:58:38,244  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:58:38,295  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 14:58:38,297  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666267058.1294963}}
2022-10-20 14:58:38,297  ### Processing group: -1001683374540
2022-10-20 14:58:38,298  Time interval not already passed. Wait 119.83146333694458 seconds.
2022-10-20 14:58:38,298  Sleeping 30 seconds.
2022-10-20 14:59:08,328  ##################### New run
2022-10-20 14:59:08,330  ##### Run updateGroupsMapping
2022-10-20 14:59:08,332  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:59:08,392  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 14:59:08,394  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666267058.1294963}}
2022-10-20 14:59:08,395  ### Processing group: -1001683374540
2022-10-20 14:59:08,395  Time interval not already passed. Wait 89.73388171195984 seconds.
2022-10-20 14:59:08,396  Sleeping 30 seconds.
2022-10-20 14:59:38,400  ##################### New run
2022-10-20 14:59:38,400  ##### Run updateGroupsMapping
2022-10-20 14:59:38,402  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 14:59:38,458  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 14:59:38,460  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666267058.1294963}}
2022-10-20 14:59:38,460  ### Processing group: -1001683374540
2022-10-20 14:59:38,461  Time interval not already passed. Wait 59.66819405555725 seconds.
2022-10-20 14:59:38,461  Sleeping 30 seconds.
2022-10-20 15:00:08,480  ##################### New run
2022-10-20 15:00:08,482  ##### Run updateGroupsMapping
2022-10-20 15:00:08,484  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 15:00:08,538  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 15:00:08,540  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666267058.1294963}}
2022-10-20 15:00:08,541  ### Processing group: -1001683374540
2022-10-20 15:00:08,542  Time interval not already passed. Wait 29.58735156059265 seconds.
2022-10-20 15:00:08,542  Sleeping 30 seconds.
2022-10-20 15:00:38,546  ##################### New run
2022-10-20 15:00:38,549  ##### Run updateGroupsMapping
2022-10-20 15:00:38,551  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 15:00:38,604  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 15:00:38,606  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666267058.1294963}}
2022-10-20 15:00:38,607  ### Processing group: -1001683374540
2022-10-20 15:00:38,607  Time interval passed. Sending message
2022-10-20 15:00:38,614  Message successfully sent.
2022-10-20 15:00:38,615  Sleeping 30 seconds.
2022-10-20 15:01:08,639  ##################### New run
2022-10-20 15:01:08,641  ##### Run updateGroupsMapping
2022-10-20 15:01:08,645  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 15:01:08,700  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 15:01:08,701  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666267238.6073337}}
2022-10-20 15:01:08,701  ### Processing group: -1001683374540
2022-10-20 15:01:08,702  Time interval not already passed. Wait 149.90507054328918 seconds.
2022-10-20 15:01:08,702  Sleeping 30 seconds.
2022-10-20 15:01:31,189  Quit
2022-10-20 15:01:33,385  ###################################################### New MAIN run
2022-10-20 15:01:33,389  Message file message.txt not found. Exiting.
2022-10-20 15:01:33,389  Picture file picturePath.txt not found. Exiting.
2022-10-20 15:01:33,389  ##################### New run
2022-10-20 15:01:33,390  ##### Run updateGroupsMapping
2022-10-20 15:01:33,391  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 15:01:33,392  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 15:01:33,578  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 15:01:33,580  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 15:01:33,580  ### Processing group: -1001683374540
2022-10-20 15:01:33,581  Time interval passed. Sending message
2022-10-20 15:01:33,588  Message successfully sent.
2022-10-20 15:01:33,588  Sleeping 30 seconds.
2022-10-20 15:02:03,596  ##################### New run
2022-10-20 15:02:03,599  ##### Run updateGroupsMapping
2022-10-20 15:02:03,602  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 15:02:03,660  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 15:02:03,662  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666267293.5810204}}
2022-10-20 15:02:03,662  ### Processing group: -1001683374540
2022-10-20 15:02:03,662  Time interval not already passed. Wait 149.9180965423584 seconds.
2022-10-20 15:02:03,663  Sleeping 30 seconds.
2022-10-20 15:02:33,692  ##################### New run
2022-10-20 15:02:33,695  ##### Run updateGroupsMapping
2022-10-20 15:02:33,699  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 15:02:33,757  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 15:02:33,759  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666267293.5810204}}
2022-10-20 15:02:33,760  ### Processing group: -1001683374540
2022-10-20 15:02:33,761  Time interval not already passed. Wait 119.82003426551819 seconds.
2022-10-20 15:02:33,761  Sleeping 30 seconds.
2022-10-20 15:02:44,741  Quit
2022-10-20 15:02:46,838  ###################################################### New MAIN run
2022-10-20 15:02:46,841  Message file message.txt not found. Exiting.
2022-10-20 15:02:46,842  Picture file picturePath.txt not found. Exiting.
2022-10-20 15:02:46,842  ##################### New run
2022-10-20 15:02:46,843  ##### Run updateGroupsMapping
2022-10-20 15:02:46,845  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 15:02:46,846  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 15:02:47,029  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 15:02:47,031  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 15:02:47,032  ### Processing group: -1001683374540
2022-10-20 15:02:47,032  Time interval passed. Sending message
2022-10-20 15:02:47,040  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 15:02:47,221  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendMessage HTTP/1.1" 200 1788
2022-10-20 15:02:47,224  Message successfully sent.
2022-10-20 15:02:47,224  Sleeping 30 seconds.
2022-10-20 15:03:17,235  ##################### New run
2022-10-20 15:03:17,236  ##### Run updateGroupsMapping
2022-10-20 15:03:17,238  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 15:03:17,302  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 15:03:17,304  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 1666267367.0328178}}
2022-10-20 15:03:17,304  ### Processing group: -1001683374540
2022-10-20 15:03:17,305  Time interval not already passed. Wait 149.72768020629883 seconds.
2022-10-20 15:03:17,305  Sleeping 30 seconds.
2022-10-20 15:03:38,967  Quit
2022-10-20 15:03:41,039  ###################################################### New MAIN run
2022-10-20 15:03:41,041  Message file message.txt not found. Exiting.
2022-10-20 15:03:41,041  Picture file picturePath.txt not found. Exiting.
2022-10-20 15:03:41,042  ##################### New run
2022-10-20 15:03:41,042  ##### Run updateGroupsMapping
2022-10-20 15:03:41,045  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 15:03:41,045  Starting new HTTPS connection (1): api.telegram.org:443
2022-10-20 15:03:41,214  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 15:03:41,216  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 15:03:41,216  ### Processing group: -1001683374540
2022-10-20 15:03:41,217  Time interval passed. Sending message
2022-10-20 15:03:41,225  Error when sending Telegram message: 'NoneType' object has no attribute 'read'
2022-10-20 15:03:41,227  Traceback (most recent call last):
  File "/var/local/bot3101f/tgsenmesph.py", line 68, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=picturePathToSend) #photo=open(picturePathToSend, "rb")
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 539, in sendPhoto
    return self._api_request_with_file('sendPhoto', _rectify(p), 'photo', photo)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 499, in _api_request_with_file
    return self._api_request(method, _rectify(params), files, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 153, in request
    fn, args, kwargs = _transform(req, **user_kw)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 118, in _transform
    fields = _compose_fields(req, **user_kw)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 84, in _compose_fields
    fields.update({k:_filetuple(k,v) for k,v in files.items()})
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 84, in <dictcomp>
    fields.update({k:_filetuple(k,v) for k,v in files.items()})
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 61, in _filetuple
    return (_guess_filename(f) or key, f.read())
AttributeError: 'NoneType' object has no attribute 'read'

2022-10-20 15:03:41,232  Error, message not sent.
2022-10-20 15:03:41,233  Sleeping 30 seconds.
2022-10-20 15:04:11,264  ##################### New run
2022-10-20 15:04:11,265  ##### Run updateGroupsMapping
2022-10-20 15:04:11,269  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 15:04:11,317  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 15:04:11,318  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 15:04:11,318  ### Processing group: -1001683374540
2022-10-20 15:04:11,319  Time interval passed. Sending message
2022-10-20 15:04:11,326  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 15:04:11,394  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 400 99
2022-10-20 15:04:11,397  Error when sending Telegram message: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})
2022-10-20 15:04:11,398  Traceback (most recent call last):
  File "/var/local/bot3101f/tgsenmesph.py", line 68, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=picturePathToSend) #photo=open(picturePathToSend, "rb")
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 539, in sendPhoto
    return self._api_request_with_file('sendPhoto', _rectify(p), 'photo', photo)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 496, in _api_request_with_file
    return self._api_request(method, _rectify(params), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})

2022-10-20 15:04:11,402  Error, message not sent.
2022-10-20 15:04:11,403  Sleeping 30 seconds.
2022-10-20 15:04:41,431  ##################### New run
2022-10-20 15:04:41,432  ##### Run updateGroupsMapping
2022-10-20 15:04:41,433  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 15:04:41,480  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 15:04:41,482  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 15:04:41,482  ### Processing group: -1001683374540
2022-10-20 15:04:41,483  Time interval passed. Sending message
2022-10-20 15:04:41,490  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 15:04:41,591  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 400 99
2022-10-20 15:04:41,592  Error when sending Telegram message: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})
2022-10-20 15:04:41,593  Traceback (most recent call last):
  File "/var/local/bot3101f/tgsenmesph.py", line 68, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=picturePathToSend) #photo=open(picturePathToSend, "rb")
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 539, in sendPhoto
    return self._api_request_with_file('sendPhoto', _rectify(p), 'photo', photo)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 496, in _api_request_with_file
    return self._api_request(method, _rectify(params), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})

2022-10-20 15:04:41,596  Error, message not sent.
2022-10-20 15:04:41,596  Sleeping 30 seconds.
2022-10-20 15:05:11,607  ##################### New run
2022-10-20 15:05:11,612  ##### Run updateGroupsMapping
2022-10-20 15:05:11,616  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 15:05:11,666  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/getUpdates HTTP/1.1" 200 383
2022-10-20 15:05:11,668  Groups: {'-1001683374540': {'messageInterval': 3, 'lastMessageTimestamp': 0}}
2022-10-20 15:05:11,669  ### Processing group: -1001683374540
2022-10-20 15:05:11,669  Time interval passed. Sending message
2022-10-20 15:05:11,677  Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
2022-10-20 15:05:11,776  https://api.telegram.org:443 "POST /bot5714149586:AAHDntl_ZxXe-BjnutLvJ0qPIepPURuZkCs/sendPhoto HTTP/1.1" 400 99
2022-10-20 15:05:11,778  Error when sending Telegram message: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})
2022-10-20 15:05:11,779  Traceback (most recent call last):
  File "/var/local/bot3101f/tgsenmesph.py", line 68, in sendTelegramMessage
    bot.sendPhoto(chatId, caption=message, photo=picturePathToSend) #photo=open(picturePathToSend, "rb")
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 539, in sendPhoto
    return self._api_request_with_file('sendPhoto', _rectify(p), 'photo', photo)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 496, in _api_request_with_file
    return self._api_request(method, _rectify(params), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python3.9/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: wrong file identifier/HTTP URL specified', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: wrong file identifier/HTTP URL specified'})

2022-10-20 15:05:11,784  Error, message not sent.
2022-10-20 15:05:11,784  Sleeping 30 seconds.
2022-10-20 15:05:18,107  Quit
